.PHONY: clean

pointerqueue:
	@chmod 755 .
	@python pointerqueuetest.py

loctree:
	@chmod 755 .
	@python loctreetest.py

lcrstree:
	@chmod 755 .
	@python lcrstreetest.py

mergelists:
	@chmod 755 .
	@python mergelists.py

listconcat:
	@chmod 755 .
	@python listconcat.py

levelorder:
	@chmod 755 .
	@python levelorder.py

preorder:
	@chmod 755 .
	@python preorder.py

huffman:
	@chmod 755 .
	@python huffman.py
