.PHONY: clean

time:
	@chmod 755 .
	@python timing.py

pointerlist:
	@chmod 755 .
	@python plisttest.py

arraylist:
	@chmod 755 .
	@python alisttest.py

pointerstack:
	@chmod 755 .
	@python pstacktest.py

arraystack:
	@chmod 755 .
	@python astacktest.py

clean:
	@\rm -f *.pyc
